config/routes.rb
LmsSystem::Application.routes.draw do
  resources :books

  devise_for :users
  get "/cart" =>"cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id" => "cart#add"

  resources :products
  resources :posts do
    resources :comments
  end

  get "create_comment" => "books#create_comment"
  post "create_comment" => "books#create_comment"

  get "page/about" => "page#about" 
  get "page/faqs" => "page#faqs"
  get "page/contact" => "page#contact"
  get "page/edit" => "page#edit"
  post "page/edit" => "page#edit"
  post "page/:id/edit" => "page#edit"

  get "page/show_users" => "page#show_users"
  post "page/show_users" => "page#show_users"

  post "posts/:id/approve" => "posts#approve"
  get "posts/:id/approve" => "posts#approve"

  get "search_result" => "books#search_result"
  post "search_result" => "books#search_result"

  get "page/edit1"

  get "/books/:id/details" => "books#details"
  post "/books/:id/details" => "books#details"

  root 'page#home'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :comments, as: :commentable
	self.inheritance_column = :_type_disabled
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def details
    @book = Book.find(params[:id])
    @book.view_count = 1 if @book.view_count.nil?
    view_count = @book.view_count + 1
    @book.update(view_count: view_count)
    if !@book.nil? && !current_user.nil?
      @comments = @book.comments.where(user_id: current_user.id)
    end
    if request.post?
      rating1 = params['rating1']
      rating2 = params['rating2']
      rating3 = params['rating3']
      rating4 = params['rating4']
      rating5 = params['rating5']
      rating6 = params['rating6']
      rating7 = params['rating7']
      rating8 = params['rating8']
      user_basics = params['user_basic']
      # "title"=>"English Grammar", "author_name"=>"", "type"=>"book", "sub_type"=>"grammar", "category"=>"english", "subcategory"=>"Geography"}
      @book.title = user_basics['title'] if !user_basics['title'].nil?
      @book.author_name = user_basics['author_name'] if !user_basics['author_name'].nil?
      @book.type = user_basics['type'] if !user_basics['type'].nil?
      @book.sub_type = user_basics['sub_type'] if !user_basics['sub_type'].nil?
      @book.category = user_basics['category'] if !user_basics['category'].nil?
      @book.subcategory = user_basics['subcategory'] if !user_basics['subcategory'].nil?

      rating1,rating2,rating3,rating4,rating5,rating6,rating7,rating8 = BooksRating.update_rating(@book.id,current_user.id,rating1,rating2,rating3,rating4,rating5,rating6,rating7,rating8)
      @book.rating1 = rating1
      @book.rating2 = rating2
      @book.rating3 = rating3
      @book.rating4 = rating4
      @book.rating5 = rating5
      @book.rating6 = rating6
      @book.rating7 = rating7
      @book.rating8 = rating8
      @book.save
      if params['commit'] == "Submit"
        if !params['comment'].nil?
          feedback = params['comment']
          Comment.create(commentable_type: 'Book',commentable_id: @book.id,user_id: current_user.id,feedback: feedback)
        else
          @message = "Comment can't be null"
        end
      end
    end
    @overall_rating = BooksRating.over_all_rating(@book.id).to_s
  end

  def search_result
    @book = ''
    @message = ''
    if !request.post?
      if !current_user.nil? && !current_user.preferences.blank?
        @book = Book.where("category = '#{current_user.preferences}' OR description = '#{current_user.preferences}'").limit(16)
      else
        @book = Book.all
      end
      if @book.blank?
        @book = Book.all.limit(16)
      end
    else
      if !params['search'].blank?
        @book = Book.where("title like '%#{params['search']}%' or category like '%#{params['search']}%' or subcategory like '%#{params['search']}%'")
      end
      if @book.blank?
        @book = Book.all
      end
      if !params['sub_type'].nil? && params['sub_type'] != '0' && (params['type'] != '1' || session['type'] != '1')
        @message = 'Sub category can only be selected under Books category'
      elsif params['sub_type'] != '0'
        @book = @book.where(sub_type: params['sub_type'])
      end
    end
    # if (session['sorting'] == params['sorting'] && !params['sorting'].nil? && params['sorting'] != '0')
    #   # @book = @book.where(sorting: params['sorting'].to_i)
    # end
    if (params['type'] == '0')
      session['type'] = '0'
    elsif (params['type'] == '1')
      session['type'] = '1'
      # @book = @book.where(types: 1)
    elsif (params['type'] == '2')
      session['type'] = '2'
      # @book = @book.where(types: 2)
    elsif (params['type'] == '3')
      session['type'] = '3'
      # @book = @book.where(types: 3)
    end
    if (session['type'] == params['type'] && !params['type'].nil? && params['type'] != '0')
      @book = @book.where(types: params['type'].to_i)
    end

    if (params['sorting'] == '0')
      session['sorting'] = '0'
    elsif (params['sorting'] == '1')
      session['sorting'] = '1'
      @book = @book.order("rating desc")
    elsif (params['sorting'] == '2')
      session['sorting'] = '2'
      @book = @book.order("view_count desc")
    end
  end

  # def create_comment
  #   binding.pry
    # if @book.nil? && !current_user.nil?
    #   @comments = @book.comments.where(user_id: current_user.id)
    # end
  #   if request.post?
  #     binding.pry
  #     Comment.create(commentable_type: 'Book',commentable_id: @book.id,user_id: current_user.id,feedback: feedback)
  #     binding.pry
  #   end
  # end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :description, :url, :image_url, :price, :category, :subcategory, :rating)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :author_name
    %br/
    = f.text_field :author_name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .field
    = f.label :image_url
    %br/
    = f.text_field :image_url
  .field
    = f.label :price
    %br/
    = f.number_field :price
  .field
    = f.label :category
    %br/
    = f.text_field :category
  .field
    = f.label :subcategory
    %br/
    = f.text_field :subcategory
  / .field
  /   = f.label :rating
  /   %br/
  /   = f.number_field :rating
  .actions
    = f.submit

app/views/books/details.html.haml
- book1 = []
- book1[@book.rating1.to_i] = true
- book2 = []
- book2[@book.rating2.to_i] = true
- book3 = []
- book3[@book.rating3.to_i] = true
- book4 = []
- book4[@book.rating4.to_i] = true
- book5 = []
- book5[@book.rating5.to_i] = true
- book6 = []
- book6[@book.rating6.to_i] = true
- book7 = []
- book7[@book.rating7.to_i] = true
- book8 = []
- book8[@book.rating8.to_i] = true

= simple_form_for (@book), :url => url_for(:action => 'details', :controller => 'books'), as: 'user_basic', method: :post  do |f|
	- if current_user.role != 'admin'
		= f.input :title, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
		= f.input :author_name, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
		= f.input :type, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
		= f.input :sub_type, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
		= f.input :category, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
		= f.input :subcategory, disabled: true,  wrapper_html: { class: 'username user-pref-email'}
	- else
		= f.input :title, wrapper_html: { class: 'username user-pref-email'}
		= f.input :author_name, wrapper_html: { class: 'username user-pref-email'}
		= f.input :type, wrapper_html: { class: 'username user-pref-email'}
		= f.input :sub_type, wrapper_html: { class: 'username user-pref-email'}
		= f.input :category, wrapper_html: { class: 'username user-pref-email'}
		= f.input :subcategory, wrapper_html: { class: 'username user-pref-email'}
	= f.label "It was detailed?"
	%input.radioStyling{checked: book1[1],:name => "rating1", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book1[2],:name => "rating1", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book1[3],:name => "rating1", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book1[4],:name => "rating1", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book1[5],:name => "rating1", :type => "radio", :value => "5"} 5

	%br/
	= f.label "Answered Questions I looking for"
	%input.radioStyling{checked: book2[1],:name => "rating2", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book2[2],:name => "rating2", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book2[3],:name => "rating2", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book2[4],:name => "rating2", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book2[5],:name => "rating2", :type => "radio", :value => "5"} 5
	
	/ = select_tag("rating2", options_for_select([['1', '1'],['2', '2'],['3','3'],['4','4'],['5','5']], @book.rating2))
	%br/
	= f.label "Easy to find material(Bibliography, Glossary, well defined index, etc)"
	%input.radioStyling{checked: book3[1],:name => "rating3", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book3[2],:name => "rating3", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book3[3],:name => "rating3", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book3[4],:name => "rating3", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book3[5],:name => "rating3", :type => "radio", :value => "5"} 5
	/ = select_tag("rating3", options_for_select([['1', '1'],['2', '2'],['3','3'],['4','4'],['5','5']], @book.rating3))
	%br/
	= f.label "It had solved examples to explain concepts"
	%input.radioStyling{checked: book4[1],:name => "rating4", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book4[2],:name => "rating4", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book4[3],:name => "rating4", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book4[4],:name => "rating4", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book4[5],:name => "rating4", :type => "radio", :value => "5"} 5
	/ # = select_tag("rating4", options_for_select([['1', '1'],['2', '2'],['3','3'],['4','4'],['5','5']], @book.rating4))
	%br/
	= f.label "It needs prior knowledge to understand concepts"
	%input.radioStyling{checked: book5[1],:name => "rating5", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book5[2],:name => "rating5", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book5[3],:name => "rating5", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book5[4],:name => "rating5", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book5[5],:name => "rating5", :type => "radio", :value => "5"} 5
	%br/
	= f.label "It has practice questions"
	%input.radioStyling{checked: book6[1],:name => "rating6", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book6[2],:name => "rating6", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book6[3],:name => "rating6", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book6[4],:name => "rating6", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book6[5],:name => "rating6", :type => "radio", :value => "5"} 5
	%br/
	= f.label "Author uses simple language to explain concepts"
	%input.radioStyling{checked: book7[1],:name => "rating7", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book7[2],:name => "rating7", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book7[3],:name => "rating7", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book7[4],:name => "rating7", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book7[5],:name => "rating7", :type => "radio", :value => "5"} 5
	%br/
	= f.label "Would you recommend this book, to someone?"
	%input.radioStyling{checked: book8[1],:name => "rating8", :type => "radio", :value => "1"} 1    
	%input.radioStyling{checked: book8[2],:name => "rating8", :type => "radio", :value => "2"} 2
	%input.radioStyling{checked: book8[3],:name => "rating8", :type => "radio", :value => "3"} 3
	%input.radioStyling{checked: book8[4],:name => "rating8", :type => "radio", :value => "4"} 4
	%input.radioStyling{checked: book8[5],:name => "rating8", :type => "radio", :value => "5"} 5
	/ # = select_tag("rating5", options_for_select([['1', '1'],['2', '2'],['3','3'],['4','4'],['5','5']], @book.rating5))
	%br/
	= fields_for @book do |fa|
		= fa.label "Over All Rating"
		= @overall_rating
	%br/
	%br/
	%a.btn.btn-sm.btn-warning{href: "/posts?category=#{@book.subcategory}", target:'_blank'}
		Related Blogs
	%a.btn.btn-sm.btn-warning.btnDown{href: @book.url, target:'_blank'}
		Download Book
	.update-book-box
		= f.button :submit, :class => "btn btn-lg btn-success"
	%head
		Comments
	%br/
	- if !@comments.nil?
		- @comments.each do |comm|
			%li{:id => "micropost-#{comm.id}"}
				%strong
					Singh
				%p.body
					#{comm.feedback}
				%p.date{:style => "text-align: right;border-bottom:2px solid black"}
					Posted #{time_ago_in_words(comm.created_at)} ago.
	%br/
	%br/
	= text_area_tag(:comment,nil, cols: "60", rows: "8")
	%br/
	= submit_tag("Submit")

app/views/books/edit.html.haml
- if !(current_user.role == 'admin')
	%h1 User doesn't have enough permission to view this page
- else
	%h1 Editing book
	= render 'form'
	= link_to 'Show', @book
	= link_to 'Back', books_path

app/views/books/index.html.haml
- if !(current_user.role == 'admin')
  %h1 User doesn't have enough permission to view this page
- else
  %h1 Listing books
  %table.books-list
    %thead
      %tr
        %th Title
        %th Description
        %th Url
        %th Image url jkehwg
        %th Price
        %th Category
        %th Subcategory
        %th Rating
        %th
        %th
        %th
    %tbody
      - @books.each do |book|
        %tr
          %td= book.title
          %td= book.description
          %td= book.url
          %td= book.image_url
          %td= book.price
          %td= book.category
          %td= book.subcategory
          %td= book.rating
          %td= link_to 'Show', book
          %td= link_to 'Edit', edit_book_path(book)
          %td= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  .new-book-box
    = link_to 'New Book', new_book_path, :class => "new-book-btn"

app/views/books/new.html.haml
- if !(current_user.role == 'admin')
	%h1 User doesn't have enough permission to view this page
- else
	%h1.new-book-title New book
	= render 'form'
	= link_to 'Back', books_path

app/views/books/search_result.html.haml
/ .blog-box
/ 	= link_to "Blog", posts_path, :class => "blog-btn"
%br/
%br/
%head
	%title Simple Search Form
= form_tag(search_result_path, :method => "post", class: "navbar-form", id: "search-form") do
	- if session['sorting'].nil?
		= select_tag("sorting",options_for_select([['Sorting','0'],['Highly Rated','1'],['Most viewed','2']],'0'))
	- else
		= select_tag("sorting",options_for_select([['Sorting','0'],['Highly Rated','1'],['Most viewed','2']],session['sorting']))
	= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Books"
	- if session['type'].nil?
		= select_tag("type", options_for_select([['Resources', '0'],['Books', '1'],['Videos', '2'],['WebLinks','3']], '0'))
	- else
		= select_tag("type", options_for_select([['Resources', '0'],['Books', '1'],['videos', '2'],['WebLinks','3']], session['type']))
	- if session['sub_type'].nil?
		= select_tag("sub_type", options_for_select([['Content Types', '0'],['textbook ', 'textbook'],['paper', 'paper'],['newspaper_article','newspaper_article'],['literature_survey','literature_survey'],['journal','journal']], '0'))
	- else
		= select_tag("sub_type", options_for_select([['Content Types', '0'],['textbook ', '1'],['paper', '2'],['newspaper_article','3'],['literature_survey','4'],['journal','5']], session['sub_type']))
	%button.btn{:type => "submit"}
		%i.icon-search
			Search
-@book.each do |article|
	.col-md-2
		.article
			%h1.article-title
				- begin
					- rating = BooksRating.over_all_rating(article.id).to_s
					- title = (article.title.to_s+"("+rating+ ' Rating'")")
				- rescue
				= link_to title, article.url, :target => "_blank"
			-if !article.image_url.blank?
				- url = "/books/#{article.id}/details"
				%a.article-img-href{href: url} 
					%img.article-img{:src => asset_path(article.image_url)}/
- if !@message.blank?
	:javascript
		window.onload = function(){
			alert("#{@message}");
		}

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @book.url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @book.subcategory %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @book.rating %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @book.title
%p
  %strong Description:
  = @book.description
%p
  %strong Url:
  = @book.url
%p
  %strong Image url:
  = @book.image_url
%p
  %strong Price:
  = @book.price
%p
  %strong Category:
  = @book.category
%p
  %strong Subcategory:
  = @book.subcategory
%p
  %strong Rating:
  = @book.rating
= link_to 'Edit', edit_book_path(@book)
|
= link_to 'Back', books_path