config/routes.rb
LmsSystem::Application.routes.draw do
  resources :books

  devise_for :users
  get "/cart" =>"cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id" => "cart#add"

  resources :products
  resources :posts do
    resources :comments
  end

  get "create_comment" => "books#create_comment"
  post "create_comment" => "books#create_comment"

  get "page/about" => "page#about" 
  get "page/faqs" => "page#faqs"
  get "page/contact" => "page#contact"
  get "page/edit" => "page#edit"
  post "page/edit" => "page#edit"
  post "page/:id/edit" => "page#edit"

  get "page/show_users" => "page#show_users"
  post "page/show_users" => "page#show_users"

  post "posts/:id/approve" => "posts#approve"
  get "posts/:id/approve" => "posts#approve"

  get "search_result" => "books#search_result"
  post "search_result" => "books#search_result"

  get "page/edit1"

  get "/books/:id/details" => "books#details"
  post "/books/:id/details" => "books#details"

  root 'page#home'

end

app/views/layouts/_header.haml
.header
	.header-top
		.header-title
			CREATIVE MINDS
			/ # = link_to "Blog", posts_path, :class => "library-btn"
		.header-login
			- if user_signed_in?
				= link_to "Sign out", destroy_user_session_path, method: :delete
			- else
				= link_to "Sign in", new_user_session_path
				= link_to "Sign up", new_user_registration_path
	.header-bottom
		.header-left
			= link_to "Home", root_path
			= link_to "Add Resource", books_path
			= link_to "User Preferences", page_edit_path
			= link_to "Blogs", posts_path
			/ # = link_to "Add New blog", new_post_path
			/ # = link_to "Add Research Paper", '/posts/new?type=paper'
			- if !current_user.nil? && (current_user.role == 'admin' || current_user.role == 'faculty')
				= link_to "Pending Blog Posts",{controller: 'posts', action: 'index',id: true},style: "color: red;"
		.header-right
			= link_to "About", page_about_path
			= link_to "Faqs", page_faqs_path
			= link_to "Contact Us", page_contact_path

app/views/layouts/_sidebar.html.erb
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", root_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com/mackenziechild">Twitter</a></li>
			<li><a href="http://instagram.com/mackenziechild">Instagram</a></li>
			<li><a href="https://github.com/mackenziechild">Github</a></li>
			<li><a href="mailto:hey@mackenziechild.me">Email</a></li>
		</ul>
	</div>
</body>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cartapp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render :partial => "/layouts/header"
    /= render :partial => "/layouts/sidebar"
    .content
      %p.notice= notice
      %p.alert= alert
      = yield
    = render :partial => '/layouts/footer'